"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Downsize.py']
APP_NAME = "Downsize"
DATA_FILES = []
OPTIONS = {'argv_emulation': True, 'includes':['os','PIL'],
'iconfile': 'downsize.icns','plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Downsize images.",
        'CFBundleIdentifier': "com.appkompaniet.osx.downsize",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': "Copyright 2018, David Szemenkar, All Rights Reserved"
    }}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
